# Generated by Django 2.0.6 on 2018-06-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectrequisition',
            name='visit_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Visit Code'),
        ),
        migrations.AddField(
            model_name='subjectrequisition',
            name='visit_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Visit Code'),
        ),
    ]
