# Generated by Django 2.0.6 on 2018-06-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_reception', '0003_auto_20180610_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectrequisition',
            name='protocol_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='protocol_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
